version: '3.8'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      # Only will build development stage from our dockerfile
      target: build
    env_file:
        - .env
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/certs
      - /app/schemas
    command: pnpm run start
    ports:
      - '4000:4000'
    depends_on:
      - redis
    networks:
      - app-network
    restart: unless-stopped
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - app-network
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    env_file:
      - .env
    healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        interval: 10s
        timeout: 5s
        retries: 5
volumes:
  nest:
  redis_data:

networks:
  app-network:
